# Generated by Django 4.2.7 on 2025-11-19 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaCoverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('type', models.CharField(choices=[('Article', 'Article'), ('Video', 'Video'), ('News', 'News'), ('Interview', 'Interview'), ('Event', 'Event')], max_length=20)),
                ('description', models.TextField()),
                ('content', models.TextField(blank=True, null=True)),
                ('youtube_video_id', models.CharField(blank=True, max_length=50, null=True)),
                ('author', models.CharField(blank=True, max_length=255, null=True)),
                ('publication', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Media Coverage',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='PromotionalContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('text', 'Text'), ('announcement', 'Announcement'), ('poster', 'Poster')], max_length=20)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('content', models.TextField()),
                ('link', models.URLField(blank=True, null=True)),
                ('link_text', models.CharField(blank=True, max_length=100, null=True)),
                ('background_color', models.CharField(blank=True, max_length=7, null=True)),
                ('text_color', models.CharField(blank=True, max_length=7, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='promotional/')),
                ('video', models.FileField(blank=True, null=True, upload_to='promotional/')),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Promotional Content',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('authors', models.JSONField(default=list)),
                ('date', models.DateField()),
                ('category', models.CharField(choices=[('Research Report', 'Research Report'), ('Policy Brief', 'Policy Brief'), ('Journal Article', 'Journal Article'), ('Working Paper', 'Working Paper'), ('Case Study', 'Case Study'), ('Methodology', 'Methodology'), ('Annual Report', 'Annual Report')], max_length=50)),
                ('type', models.CharField(choices=[('PDF', 'PDF'), ('DOCX', 'DOCX'), ('XLSX', 'XLSX'), ('PPTX', 'PPTX'), ('Link', 'Link')], max_length=10)),
                ('sector', models.CharField(choices=[('Health', 'Health'), ('Social', 'Social'), ('Environment', 'Environment'), ('Research', 'Research'), ('Policy', 'Policy')], max_length=50)),
                ('file', models.FileField(blank=True, null=True, upload_to='publications/')),
                ('external_url', models.URLField(blank=True, null=True)),
                ('pages', models.IntegerField(blank=True, null=True)),
                ('language', models.CharField(default='English', max_length=50)),
                ('publisher', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Publications',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='RelevantLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('url', models.URLField()),
                ('category', models.CharField(choices=[('National', 'National'), ('International', 'International'), ('Government', 'Government'), ('Research', 'Research'), ('NGO', 'NGO'), ('Academic', 'Academic')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Relevant Links',
                'ordering': ['category', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ResearchArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(choices=[('health', 'Health, Mental Health & Social Health'), ('climate', 'Climate Change Impacts on Health & Livelihood'), ('inequality', 'Social & Familial Impacts of Inequality')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('content', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='research/')),
                ('author', models.CharField(blank=True, max_length=255, null=True)),
                ('youtube_video_id', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Research Items',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ResourcePanel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('bio', models.TextField()),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='resource_panel/')),
                ('expertise', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Resource Panel',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Completed', 'Completed'), ('Upcoming', 'Upcoming')], max_length=20)),
                ('category', models.CharField(max_length=100)),
                ('participants', models.IntegerField(blank=True, default=0, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='surveys/')),
                ('author', models.CharField(blank=True, max_length=255, null=True)),
                ('methodology', models.TextField(blank=True, null=True)),
                ('findings', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Surveys',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Webinar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date', models.CharField(max_length=255)),
                ('duration', models.CharField(blank=True, max_length=50, null=True)),
                ('presenter_name', models.CharField(max_length=255)),
                ('presenter_title', models.CharField(blank=True, max_length=255, null=True)),
                ('presenter_bio', models.TextField(blank=True, null=True)),
                ('topics', models.JSONField(default=list)),
                ('registration_link', models.URLField(blank=True, null=True)),
                ('recording_link', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Upcoming', 'Upcoming'), ('Ongoing', 'Ongoing'), ('Completed', 'Completed')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Webinars',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SurveyTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='api.survey')),
            ],
        ),
        migrations.CreateModel(
            name='SurveyObjective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objective', models.TextField()),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objectives', to='api.survey')),
            ],
        ),
        migrations.CreateModel(
            name='SurveyExternalLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_links', to='api.survey')),
            ],
        ),
        migrations.CreateModel(
            name='ResearchTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('research', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='api.researcharea')),
            ],
        ),
        migrations.CreateModel(
            name='ResearchExternalLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('research', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_links', to='api.researcharea')),
            ],
        ),
        migrations.CreateModel(
            name='RelevantLinkTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='api.relevantlink')),
            ],
        ),
        migrations.CreateModel(
            name='PublicationTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='api.publication')),
            ],
        ),
        migrations.CreateModel(
            name='MediaTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='api.mediacoverage')),
            ],
        ),
        migrations.CreateModel(
            name='MediaExternalLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_links', to='api.mediacoverage')),
            ],
        ),
    ]
