# Generated by Django 4.2.7 on 2025-11-19 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='researcharea',
            name='image_layout',
            field=models.CharField(choices=[('gallery', 'Gallery View'), ('distributed', 'Distributed in Content'), ('single', 'Single Featured Image')], default='single', max_length=20),
        ),
        migrations.CreateModel(
            name='ResearchImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='research/images/')),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('research', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.researcharea')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
