# Generated by Django 4.2.7 on 2025-11-21 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_promotionalcontent_type_alter_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('content_type', models.CharField(choices=[('chairman_intro', 'Chairman Introduction'), ('organization_intro', 'Organization Introduction'), ('history', 'History'), ('achievements', 'Achievements'), ('custom', 'Custom Content')], default='custom', max_length=50)),
                ('content', models.TextField(help_text='Main content text (supports HTML)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('image_position', models.CharField(choices=[('left', 'Left'), ('right', 'Right'), ('top', 'Top'), ('bottom', 'Bottom')], default='left', help_text='Image position relative to content', max_length=20)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'About Page Content',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='AboutPageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('section_type', models.CharField(choices=[('vision', 'Vision'), ('mission', 'Mission'), ('goals', 'Goals'), ('objectives', 'Objectives'), ('values', 'Values'), ('custom', 'Custom Section')], default='custom', max_length=50)),
                ('items', models.JSONField(default=list, help_text='List of items/bullet points for this section')),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'About Page Sections',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationalMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=255)),
                ('bio', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='organizational/')),
                ('level', models.IntegerField(default=0, help_text='Hierarchy level (0 = top level, 1 = second level, etc.)')),
                ('order', models.IntegerField(default=0, help_text='Display order within the same level')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reports_to', models.ForeignKey(blank=True, help_text='The person this member reports to (for hierarchy)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to='api.organizationalmember')),
            ],
            options={
                'verbose_name_plural': 'Organizational Members',
                'ordering': ['level', 'order', 'name'],
            },
        ),
    ]
