# Generated by Django 4.2.7 on 2025-11-21 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_aboutpagecontent_aboutpagesection_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutpagecontent',
            options={'ordering': ['order', 'title'], 'verbose_name': 'About Content', 'verbose_name_plural': 'ℹ️ About - Content'},
        ),
        migrations.AlterModelOptions(
            name='aboutpagesection',
            options={'ordering': ['order', 'title'], 'verbose_name': 'About Section', 'verbose_name_plural': 'ℹ️ About - Sections'},
        ),
        migrations.AlterModelOptions(
            name='mediacoverage',
            options={'ordering': ['-date'], 'verbose_name': 'Media Coverage Item', 'verbose_name_plural': '📰 Media Coverage'},
        ),
        migrations.AlterModelOptions(
            name='organizationalmember',
            options={'ordering': ['level', 'order', 'name'], 'verbose_name': 'Organizational Member', 'verbose_name_plural': 'ℹ️ About - Organizational Structure'},
        ),
        migrations.AlterModelOptions(
            name='promotionalcontent',
            options={'ordering': ['order', '-created_at'], 'verbose_name': 'Promotional Content', 'verbose_name_plural': '🎨 Promotional Content'},
        ),
        migrations.AlterModelOptions(
            name='publication',
            options={'ordering': ['-date'], 'verbose_name': 'Publication', 'verbose_name_plural': '📚 Publications'},
        ),
        migrations.AlterModelOptions(
            name='relevantlink',
            options={'ordering': ['category', 'title'], 'verbose_name': 'Relevant Link', 'verbose_name_plural': '🔗 Relevant Links'},
        ),
        migrations.AlterModelOptions(
            name='researcharea',
            options={'ordering': ['-date'], 'verbose_name': 'Research Item', 'verbose_name_plural': '🔬 Research'},
        ),
        migrations.AlterModelOptions(
            name='resourcepanel',
            options={'ordering': ['name'], 'verbose_name': 'Resource Panel Member', 'verbose_name_plural': '👥 Resource Panel'},
        ),
        migrations.AlterModelOptions(
            name='survey',
            options={'ordering': ['-date'], 'verbose_name': 'Survey', 'verbose_name_plural': '📊 Surveys'},
        ),
        migrations.AlterModelOptions(
            name='webinar',
            options={'ordering': ['-created_at'], 'verbose_name': 'Webinar', 'verbose_name_plural': '🎥 Webinars'},
        ),
    ]
