# Generated by Django 4.2.7 on 2025-11-22 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_aboutpagecontent_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_title', models.CharField(default='About Thoughts & Thorough', max_length=255)),
                ('about_description', models.TextField(default='Evidence-based research and consultancy services for a sustainable future. We conduct rigorous surveys, comprehensive studies, and provide strategic consultancy grounded in data and environmental awareness.')),
                ('facebook_url', models.URLField(blank=True, null=True)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('youtube_url', models.URLField(blank=True, null=True)),
                ('twitter_url', models.URLField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('research_areas_links', models.JSONField(default=list, help_text="List of research area links: [{'title': 'Link Title', 'url': '/path'}]")),
                ('publications_links', models.JSONField(default=list, help_text="List of publication links: [{'title': 'Link Title', 'url': '/path'}]")),
                ('copyright_text', models.CharField(default='Thoughts & Thorough. All rights reserved.', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Footer',
                'verbose_name_plural': '🦶 Footer',
                'ordering': ['-updated_at'],
            },
        ),
    ]
