# Generated by Django 4.2.7 on 2025-11-22 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_footer'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('document_type', models.CharField(choices=[('Certificate', 'Certificate'), ('Audit Report', 'Audit Report'), ('Approval', 'Approval'), ('License', 'License')], max_length=50)),
                ('year', models.CharField(help_text="Year of the document (e.g., '2023')", max_length=4)),
                ('file', models.FileField(blank=True, null=True, upload_to='legal_documents/')),
                ('external_url', models.URLField(blank=True, help_text='External URL if document is hosted elsewhere', null=True)),
                ('issued_by', models.CharField(blank=True, help_text='Organization that issued the document', max_length=255, null=True)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, help_text='Expiry date if applicable', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Legal Document',
                'verbose_name_plural': '📄 Legal Documents & Certifications',
                'ordering': ['-year', 'order', 'title'],
            },
        ),
    ]
