# Generated by Django 4.2.7 on 2025-11-22 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_legaldocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(default='Get In Touch', max_length=255)),
                ('hero_description', models.TextField(default="We'd love to hear from you. Reach out to us for research collaborations, consultancy services, or general inquiries.")),
                ('contact_section_title', models.CharField(default='Contact Information', max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('facebook_url', models.URLField(blank=True, null=True)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('youtube_url', models.URLField(blank=True, null=True)),
                ('twitter_url', models.URLField(blank=True, null=True)),
                ('form_title', models.CharField(default='Send Us a Message', max_length=255)),
                ('form_submit_button_text', models.CharField(default='Send Message', max_length=100)),
                ('additional_contact_methods', models.JSONField(blank=True, default=list, help_text="List of additional contact methods: [{'type': 'WhatsApp', 'label': 'WhatsApp', 'value': '+1234567890', 'url': 'https://wa.me/1234567890'}]")),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contact Page',
                'verbose_name_plural': '📧 Contact Page',
                'ordering': ['-updated_at'],
            },
        ),
    ]
